# Site settings
title: on the code...
email: baris [at] onehundredyearsofcode.com
description: Writings and how-to's for everyday programmer with a curious mind.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://onthecode.com" # the base hostname & protocol for your site
twitter_username: baris_wonders
github_username:  byuksel
excerpt_separator: <!--more-->
# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap