# Site settings
title: On the code...
email: #your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://onthecode.com" # the base hostname & protocol for your site
twitter_username: baris_wonders
github_username:  byuksel
excerpt_separator: <!--more-->
# Build settings
markdown: kramdown
